/*
    skript pro inicializaci Thalie craftu (tc)
    31.3.2008 Melvik
*/
#include "tc_constants"


void initPrices();
/*
    Pri startu serveru tato priradi resrefum itemu alchimystycke vlastnosti
    toto prirazeni bude v promenych na modulu ve tvaru
    ALCH_INREDIENCE_PREFIX + ResReF = string vlastnosti (napr. ai1010002003)
*/
void initIgredientsProperties();


void main()
{
    initPrices();
    initIgredientsProperties();
}


void initPrices()
{
    string MATERIAL_PRICE = "material price";
    float no_nasobitel = 0.25;
    object oModule = GetModule();
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut1",FloatToInt(5*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut2",FloatToInt(10*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut3",FloatToInt(20*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut4",FloatToInt(80*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut11",FloatToInt(120*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut8",FloatToInt(160*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut7",FloatToInt(250*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut5",FloatToInt(500*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut10",FloatToInt(600*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut9",FloatToInt(700*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut12",FloatToInt(1500*no_nasobitel));
    SetLocalInt(oModule,MATERIAL_PRICE + "tc_prut13",FloatToInt(2500*no_nasobitel));
}


void initIgredientsProperties()
{
    object oModule = GetModule();


// GENEROVANY KOD - NEPREPISOVAT (mozna uprava v exelu)
/* vlastnosti alchymistickych ingredienci start*/
/*
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnraloeleaf", "ai1025027045008004021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrthistleleaf", "ai1024072074016004021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina009", "ai1025032044055071008004");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina013", "ai1024086077073072065002113");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrblkcohoshroot", "ai2024026033042057016004");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba007", "ai1023035038039050051019018");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba005", "ai1022043066067069004002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba014", "ai1023053078079080082083085");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba008", "ai2023028034046049056019002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "me_ethetzl", "ai2030036058020019021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroomwht", "ai3030048058060070020019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroomblk", "ai3024037052072016019021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroomspot", "ai2023028034038039040075019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroomyel", "ai3029007095004015013009097");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroompurp", "ai3022062076005019021002111");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrmushroomred", "ai2023028034049019021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrlumpofclay", "ai2024057073016019021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_sliz_ichor", "ai3022062066076005019108");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "nw_it_msmlmisc25", "ai3022062066076005019108");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_ghoul_jatra", "ai1030054084020005019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_alcjedvak2", "ai1029007105106088087095004094");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_alcjedvak3", "ai1029099105029094004006015");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_alcjedvak1", "ai1029099089090091004013009");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina001", "ai1025027045008002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina008", "ai2023028035038046075019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "me_kloubk", "ai1030036054060064020005");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrcomfryroot", "ai1029100106096004015018");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrechinacearoot", "ai1022067005004002108112");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrginsengroot", "ai1025032044047055008071");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrgingerroot", "ai1029100106097004015013002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba009", "ai1025027044045047055071008002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina012", "ai1023053078079080082083085");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_mrchzr_krev", "ai3024026037052016042");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrhopsflower", "ai2025008004019002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrcalendulafwr", "ai2024074016004018019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrcatnipleaf", "ai1022066005004018019111");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrhazelleaf", "ai1024026033016004018021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrskullcapleaf", "ai1022043059005004018021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrcloverleaf", "ai1025027008021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrnettleleaf", "ai1029101089090091004009");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrpepmintleaf", "ai1025027008018002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrsageleaf", "ai1025032047008004");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_drap_maso", "ai1030048054020004018021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina002", "ai1024026031037061016");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba002", "ai2023028035046019004018");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina006", "ai1022043068069005004018021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina004", "ai1023040049050056019018");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba004", "ai1022041059062067069076110");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrspidersilk", "ai2024031042065016002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba010", "ai1024026031061074016");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina005", "ai1029101088004006013099");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "peri_plivnika", "ai1030048020021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba013", "ai1024086077073072065113");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_troproryt", "ai1030063064081020005021");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "sporymykoida", "ai2022043068005018002111112");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_popsl_vyh", "ai2024042061016004002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_vino_spory", "ai2024042061016004002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "ry_srdce_meph", "ai1022059068005004019109112");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba006", "ai1024033057074016002042");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrgarlicclove", "ai1022041005004018110108109");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina003", "ai1022041067069004110");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba015", "ai2023049051053056075019002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina011", "ai3023028050051056019002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina010", "ai2023034035039046051053019");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_bylina007", "ai3029102029004006015013");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba001", "ai1025027032044045008018");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba003", "ai2023028040050019004053");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "nw_it_msmlmisc06", "ai1030063070020005004021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "kh_zublicha", "ai1030081084020005019021002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "zihadlo_vosy", "ai1029102087004006015009");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrchamomilefwr", "ai1025027032018019002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrhawthornfwr", "ai1029103094004006013009018002");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba011", "ai1029103104106089090091096004");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "tc_houba012", "ai1029104088087094097004006");
SetLocalString(oModule, ALCH_INREDIENCE_PREFIX + "cnrangelicaleaf", "ai1025027032018019002");
*/


/* vlastnosti alchymistickych ingredienci END*/

/* alchymisticke vlastnosti START*/
/*
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "001", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "001", "bu");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "002", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "002", "nti");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "003", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "003", "mek");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "004", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "004", "dis");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "005", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "005", "kle");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "006", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "006", "sra");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "007", 21);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "007", "has");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "008", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "008", "amy");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "009", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "009", "ate");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "010", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "010", "ahy");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "011", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "011", "ate");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "012", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "012", "astr");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "013", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "013", "aorl");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "014", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "014", "asov");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "015", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "015", "alis");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "016", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "016", "akoc");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "017", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "017", "asil");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "018", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "018", "atrolo");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "019", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "019", "zle");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "020", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "020", "zva");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "021", 0);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "021", "zkri");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "022", 3);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "022", "sol");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "023", 4);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "023", "rez");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "024", 5);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "024", "chmug");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "025", 6);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "025", "li");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "026", 10);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "026", "tvr");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "027", 12);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "027", "lel");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "028", 15);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "028", "poz");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "029", 15);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "029", "breke");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "030", 17);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "030", "lema");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "031", 20);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "031", "nev");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "032", 22);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "032", "les");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "033", 23);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "033", "kane");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "034", 25);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "034", "orl");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "035", 26);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "035", "sov");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "036", 26);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "036", "zosm");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "037", 26);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "037", "vdu");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "038", 27);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "038", "lis");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "039", 28);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "039", "koc");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "040", 29);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "040", "sil");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "041", 29);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "041", "buch");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "042", 30);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "042", "ku");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "043", 31);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "043", "ope");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "044", 32);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "044", "trolo");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "045", 33);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "045", "lev");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "046", 34);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "046", "omy");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "047", 35);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "047", "tret");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "048", 39);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "048", "fa");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "049", 36);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "049", "ote");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "050", 37);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "050", "bop");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "051", 40);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "051", "ohy");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "052", 38);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "052", "prone");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "053", 42);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "053", "sko");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "054", 43);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "054", "ost");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "055", 44);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "055", "lek");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "056", 46);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "056", "bosi");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "057", 45);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "057", "kmn");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "058", 47);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "058", "vopo");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "059", 48);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "059", "osti");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "060", 50);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "060", "dis");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "061", 53);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "061", "vyne");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "062", 52);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "062", "zeo");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "063", 51);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "063", "man");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "064", 55);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "064", "cim");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "065", 57);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "065", "nahle");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "066", 56);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "066", "zec");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "067", 58);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "067", "zee");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "068", 59);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "068", "kysti");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "069", 60);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "069", "zek");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "070", 62);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "070", "dewa");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "071", 63);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "071", "leu");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "072", 65);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "072", "prt");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "073", 67);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "073", "skam");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "074", 69);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "074", "kama");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "075", 70);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "075", "ste");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "076", 72);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "076", "thu");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "077", 73);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "077", "pravi");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "078", 75);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "078", "orl");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "079", 76);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "079", "sov");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "080", 77);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "080", "lis");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "081", 78);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "081", "shash");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "082", 79);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "082", "koc");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "083", 81);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "083", "sil");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "084", 85);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "084", "grema");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "085", 88);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "085", "boz");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "086", 90);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "086", "trago");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "087", 26);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "087", "umreke");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "088", 16);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "088", "motreke");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "089", 11);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "089", "fujeke");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "090", 14);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "090", "chyteke");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "091", 12);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "091", "pajeke");

SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "094", 8);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "094", "craw");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "095", 5);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "095", "taggit");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "096", 17);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "096", "pifi");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "097", 13);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "097", "sassonne");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "098", 21);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "098", "haunsp");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "099", 14);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "099", "jhuil");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "100", 16);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "100", "kamma");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "101", 30);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "101", "mordva");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "102", 12);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "102", "katak");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "103", 29);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "103", "rhul");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "104", 27);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "104", "sezar");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "105", 21);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "105", "ziran");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "106", 6);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "106", "place");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "107", 34 );
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "107", "sze");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "108", 35);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "108", "sle");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "109", 36);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "109", "svz");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "110", 37);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "110", "soh");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "111", 24);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "111", "sdo");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "112", 25);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "112", "szl");
SetLocalInt(oModule, ALCH_PROPERTY_STR_PREFIX + "113", 80);
SetLocalString(oModule, ALCH_PROPERTY_NAME_PREFIX + "113", "pøed");
*/

/* alchymisticke vlastnosti END*/

/* TROFEJE START - generovano exelem */
/*
SetLocalString(oModule, "thTrofejMisc_ry_sn_zmije", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_medforest001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_obrihad", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_hugefores001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_hugejungl001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_medjungle001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_tinyjungl001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_zep_hugedeser001", "ry_hadi_kuze");
SetLocalString(oModule, "thTrofejMisc_staryjezevec", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_staryjezevec", "1");
SetLocalString(oModule, "thTrofejMisc_cnrabadger", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_cnrabadger", "1");
SetLocalString(oModule, "thTrofejMisc_badger001", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_badger001", "1");
SetLocalString(oModule, "thTrofejMisc_badger_friendly", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_badger_friendly", "1");
SetLocalString(oModule, "thTrofejMisc_nw_badger", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_nw_badger", "1");
SetLocalString(oModule, "thTrofejMisc_nw_direbadg", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_nw_direbadg", "1");
SetLocalString(oModule, "thTrofejMisc_cnracragcat", "cnrskincragcat");
SetLocalInt(oModule, "thTrofejDiff_cnracragcat", 50);
SetLocalString(oModule, "thTrofejMisc_nw_cougar", "cnrskincragcat");
SetLocalInt(oModule, "thTrofejDiff_nw_cougar", 50);
SetLocalString(oModule, "thTrofejMisc_cnracougar", "cnrskincragcat");
SetLocalInt(oModule, "thTrofejDiff_cnracougar", 50);
SetLocalString(oModule, "thTrofejMisc_nw_rat001", "cnrskinrat");
SetLocalString(oModule, "thTrofejMisc_nw_rat002", "cnrskinrat");
SetLocalString(oModule, "thTrofejMisc_nw_ratdire001", "cnrskinrat");
SetLocalString(oModule, "thTrofejMisc_cnrskinpolarbear", "cnrskinpolarbear");
SetLocalString(oModule, "thTrofejMeat_cnrskinpolarbear", "2");
SetLocalInt(oModule, "thTrofejDiff_cnrskinpolarbear", 230);
SetLocalString(oModule, "thTrofejMisc_nw_bearpolar", "cnrskinpolarbear");
SetLocalString(oModule, "thTrofejMeat_nw_bearpolar", "2");
SetLocalInt(oModule, "thTrofejDiff_nw_bearpolar", 230);
SetLocalString(oModule, "thTrofejMisc_ry_sn_medved", "cnrskinpolarbear");
SetLocalString(oModule, "thTrofejMeat_ry_sn_medved", "2");
SetLocalInt(oModule, "thTrofejDiff_ry_sn_medved", 230);
SetLocalString(oModule, "thTrofejMisc_ry_pr_medved", "cnrskinblkbear");
SetLocalString(oModule, "thTrofejMeat_ry_pr_medved", "2");
SetLocalInt(oModule, "thTrofejDiff_ry_pr_medved", 100);
SetLocalString(oModule, "thTrofejMisc_cnrablkbear", "cnrskinblkbear");
SetLocalString(oModule, "thTrofejMeat_cnrablkbear", "2");
SetLocalInt(oModule, "thTrofejDiff_cnrablkbear", 100);
SetLocalString(oModule, "thTrofejMisc_nw_bearblck", "cnrskinblkbear");
SetLocalString(oModule, "thTrofejMeat_nw_bearblck", "2");
SetLocalInt(oModule, "thTrofejDiff_nw_bearblck", 100);
SetLocalString(oModule, "thTrofejMisc_bearblck001", "cnrskinblkbear");
SetLocalString(oModule, "thTrofejMeat_bearblck001", "2");
SetLocalInt(oModule, "thTrofejDiff_bearblck001", 150);
SetLocalString(oModule, "thTrofejMisc_cnrabrnbear", "cnrskinbrnbear");
SetLocalString(oModule, "thTrofejMeat_cnrabrnbear", "2");
SetLocalInt(oModule, "thTrofejDiff_cnrabrnbear", 150);
SetLocalString(oModule, "thTrofejMisc_bearbrwn001", "cnrskinbrnbear");
SetLocalString(oModule, "thTrofejMeat_bearbrwn001", "2");
SetLocalInt(oModule, "thTrofejDiff_bearbrwn001", 150);
SetLocalString(oModule, "thTrofejMisc_nw_bearbrwn", "cnrskinbrnbear");
SetLocalString(oModule, "thTrofejMeat_nw_bearbrwn", "2");
SetLocalInt(oModule, "thTrofejDiff_nw_bearbrwn", 150);
SetLocalString(oModule, "thTrofejMisc_bearbrwn002", "cnrskinbrnbear");
SetLocalString(oModule, "thTrofejMeat_bearbrwn002", "2");
SetLocalInt(oModule, "thTrofejDiff_bearbrwn002", 200);
SetLocalString(oModule, "thTrofejMisc_nw_bearkodiak", "cnrskingrizbear");
SetLocalString(oModule, "thTrofejMeat_nw_bearkodiak", "2");
SetLocalInt(oModule, "thTrofejDiff_nw_bearkodiak", 200);
SetLocalString(oModule, "thTrofejMisc_cnragrizbear", "cnrskingrizbear");
SetLocalString(oModule, "thTrofejMeat_cnragrizbear", "2");
SetLocalInt(oModule, "thTrofejDiff_cnragrizbear", 200);
SetLocalString(oModule, "thTrofejMisc_bearkodiak002", "cnrskingrizbear");
SetLocalString(oModule, "thTrofejMeat_bearkodiak002", "2");
SetLocalInt(oModule, "thTrofejDiff_bearkodiak002", 200);
SetLocalString(oModule, "thTrofejMisc_beardire001", "cnrskindb");
SetLocalString(oModule, "thTrofejMeat_beardire001", "3");
SetLocalInt(oModule, "thTrofejDiff_beardire001", 280);
SetLocalString(oModule, "thTrofejMisc_beardireboss001", "cnrskindb");
SetLocalString(oModule, "thTrofejMeat_beardireboss001", "3");
SetLocalInt(oModule, "thTrofejDiff_beardireboss001", 280);
SetLocalString(oModule, "thTrofejMisc_leopard", "cnrskinleopard");
SetLocalString(oModule, "thTrofejMeat_leopard", "1");
SetLocalInt(oModule, "thTrofejDiff_leopard", 100);
SetLocalString(oModule, "thTrofejMisc_zep_catcloudl001", "cnrskinleopard");
SetLocalString(oModule, "thTrofejMeat_zep_catcloudl001", "1");
SetLocalInt(oModule, "thTrofejDiff_zep_catcloudl001", 100);
SetLocalString(oModule, "thTrofejMisc_diretiger001", "cnrskintiger");
SetLocalString(oModule, "thTrofejMeat_diretiger001", "3");
SetLocalInt(oModule, "thTrofejDiff_diretiger001", 300);
SetLocalString(oModule, "thTrofejMisc_zep_cattiger001", "me_kuze_tygr");
SetLocalString(oModule, "thTrofejMeat_zep_cattiger001", "1");
SetLocalInt(oModule, "thTrofejDiff_zep_cattiger001", 200);
SetLocalString(oModule, "thTrofejMisc_zep_cattiger", "me_kuze_tygr");
SetLocalString(oModule, "thTrofejMeat_zep_cattiger", "1");
SetLocalInt(oModule, "thTrofejDiff_zep_cattiger", 200);
SetLocalString(oModule, "thTrofejMisc_cnralion", "cnrskinlion");
SetLocalString(oModule, "thTrofejMeat_cnralion", "1");
SetLocalInt(oModule, "thTrofejDiff_cnralion", 300);
SetLocalString(oModule, "thTrofejMisc_zep_bat_003", "cnrskinbat");
SetLocalString(oModule, "thTrofejMisc_zep_bat_004", "cnrskinbat");
SetLocalString(oModule, "thTrofejMisc_nw_bat", "cnrskinbat");
SetLocalString(oModule, "thTrofejMisc_ry_karnetop", "cnrskinbat");
SetLocalString(oModule, "thTrofejMisc_cnrapanther", "cnrskinpanther");
SetLocalString(oModule, "thTrofejMeat_cnrapanther", "1");
SetLocalInt(oModule, "thTrofejDiff_cnrapanther", 120);
SetLocalString(oModule, "thTrofejMisc_panther001", "cnrskinpanther");
SetLocalString(oModule, "thTrofejMeat_panther001", "1");
SetLocalInt(oModule, "thTrofejDiff_panther001", 120);
SetLocalString(oModule, "thTrofejMisc_panther2", "cnrskinpanther");
SetLocalString(oModule, "thTrofejMeat_panther2", "1");
SetLocalInt(oModule, "thTrofejDiff_panther2", 120);
SetLocalString(oModule, "thTrofejMisc_bearkodiak001", "cnrskinpanther");
SetLocalString(oModule, "thTrofejMeat_bearkodiak001", "1");
SetLocalInt(oModule, "thTrofejDiff_bearkodiak001", 120);
SetLocalString(oModule, "thTrofejMisc_boar001", "cnrskinboar");
SetLocalString(oModule, "thTrofejMeat_boar001", "1");
SetLocalInt(oModule, "thTrofejDiff_boar001", 20);
SetLocalString(oModule, "thTrofejMisc_cnraboar", "cnrskinboar");
SetLocalString(oModule, "thTrofejMeat_cnraboar", "1");
SetLocalInt(oModule, "thTrofejDiff_cnraboar", 20);
SetLocalString(oModule, "thTrofejMisc_boardire001", "cnrskinboar");
SetLocalString(oModule, "thTrofejMeat_boardire001", "1");
SetLocalInt(oModule, "thTrofejDiff_boardire001", 20);
SetLocalString(oModule, "thTrofejMisc_nw_boardire", "cnrskinboar");
SetLocalString(oModule, "thTrofejMeat_nw_boardire", "1");
SetLocalInt(oModule, "thTrofejDiff_nw_boardire", 20);
SetLocalString(oModule, "thTrofejMisc_nw_wolf", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_nw_wolf", "1");
SetLocalInt(oModule, "thTrofejDiff_nw_wolf", 15);
SetLocalString(oModule, "thTrofejMisc_direwolf002", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_direwolf002", "1");
SetLocalInt(oModule, "thTrofejDiff_direwolf002", 15);
SetLocalString(oModule, "thTrofejMisc_cnrawolf", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_cnrawolf", "1");
SetLocalInt(oModule, "thTrofejDiff_cnrawolf", 15);
SetLocalString(oModule, "thTrofejMisc_direbadg003", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_direbadg003", "1");
SetLocalInt(oModule, "thTrofejDiff_direbadg003", 15);
SetLocalString(oModule, "thTrofejMisc_vlkvudcesmecky", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_vlkvudcesmecky", "1");
SetLocalInt(oModule, "thTrofejDiff_vlkvudcesmecky", 15);
SetLocalString(oModule, "thTrofejMisc_wolfdireboss002", "cnrskinwolf");
SetLocalString(oModule, "thTrofejMeat_wolfdireboss002", "1");
SetLocalInt(oModule, "thTrofejDiff_wolfdireboss002", 15);
SetLocalString(oModule, "thTrofejMisc_nw_ox", "cnrskinox");
SetLocalString(oModule, "thTrofejMeat_nw_ox", "2");
SetLocalString(oModule, "thTrofejMisc_cnraox", "cnrskinox");
SetLocalString(oModule, "thTrofejMeat_cnraox", "2");
SetLocalString(oModule, "thTrofejMisc_nw_wolfwint", "cnrskinwinwolf");
SetLocalString(oModule, "thTrofejMeat_nw_wolfwint", "1");
SetLocalInt(oModule, "thTrofejDiff_nw_wolfwint", 200);
SetLocalString(oModule, "thTrofejMisc_ry_snez_tygr", "ry_snt_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_snez_tygr", "2");
SetLocalInt(oModule, "thTrofejDiff_ry_snez_tygr", 300);
SetLocalString(oModule, "thTrofejMisc_ry_zur_gor_2", "ry_gor_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_zur_gor_2", "2");
SetLocalInt(oModule, "thTrofejDiff_ry_zur_gor_2", 160);
SetLocalString(oModule, "thTrofejMisc_ry_koc_savl", "ry_szkoc_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_koc_savl", "2");
SetLocalInt(oModule, "thTrofejDiff_ry_koc_savl", 150);
SetLocalString(oModule, "thTrofejMisc_ry_sn_leopard2", "ry_snl_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_sn_leopard2", "1");
SetLocalInt(oModule, "thTrofejDiff_ry_sn_leopard2", 100);
SetLocalString(oModule, "thTrofejMisc_zep_catleopar001", "ry_snl_kuze");
SetLocalString(oModule, "thTrofejMeat_zep_catleopar001", "1");
SetLocalInt(oModule, "thTrofejDiff_zep_catleopar001", 100);
SetLocalString(oModule, "thTrofejMisc_ry_zraljes", "ry_zral_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_zraljes", "1");
SetLocalInt(oModule, "thTrofejDiff_ry_zraljes", 150);
SetLocalString(oModule, "thTrofejMisc_ry_krab", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_ry_krab", 10);
SetLocalString(oModule, "thTrofejMisc_ry_poukrab", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_ry_poukrab", 10);
SetLocalString(oModule, "thTrofejMisc_ry_poukrab001", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_ry_poukrab001", 10);
SetLocalString(oModule, "thTrofejMisc_zep_crab002", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_zep_crab002", 10);
SetLocalString(oModule, "thTrofejMisc_zep_crab003", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_zep_crab003", 10);
SetLocalString(oModule, "thTrofejMisc_zep_crab004", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_zep_crab004", 250);
SetLocalString(oModule, "thTrofejMisc_beldskyorel", "it_amt_feath001");
SetLocalInt(oModule, "thTrofejDiff_beldskyorel", 250);
SetLocalString(oModule, "thTrofejMisc_zep_antelope", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_antelope", "1");
SetLocalString(oModule, "thTrofejMisc_zep_gazelle001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_gazelle001", "1");
SetLocalString(oModule, "thTrofejMisc_ry_bila_opice", "kuze");
SetLocalString(oModule, "thTrofejMeat_ry_bila_opice", "1");
SetLocalString(oModule, "thTrofejMisc_direbadg001", "kuze");
SetLocalString(oModule, "thTrofejMeat_direbadg001", "1");
SetLocalString(oModule, "thTrofejMisc_direbadg002", "kuze");
SetLocalString(oModule, "thTrofejMeat_direbadg002", "1");
SetLocalString(oModule, "thTrofejMisc_zep_ferret001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_ferret001", "1");
SetLocalString(oModule, "thTrofejMisc_zep_ferret001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_ferret001", "1");
SetLocalString(oModule, "thTrofejMisc_zep_hyenaspot001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_hyenaspot001", "1");
SetLocalString(oModule, "thTrofejMisc_ry_motak2", "kuze");
SetLocalString(oModule, "thTrofejMeat_ry_motak2", "1");
SetLocalString(oModule, "thTrofejMisc_ry_motak3", "kuze");
SetLocalString(oModule, "thTrofejMeat_ry_motak3", "1");
SetLocalString(oModule, "thTrofejMisc_zep_ringtail001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_ringtail001", "1");
SetLocalString(oModule, "thTrofejMisc_zep_raccoon001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_raccoon001", "1");
SetLocalString(oModule, "thTrofejMisc_zep_mink001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_mink001", "1");
SetLocalString(oModule, "thTrofejMisc_ry_opice1", "kuze");
SetLocalString(oModule, "thTrofejMeat_ry_opice1", "1");
SetLocalString(oModule, "thTrofejMisc_zep_skunk", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_skunk", "1");
SetLocalString(oModule, "thTrofejMisc_zep_weasel001", "kuze");
SetLocalString(oModule, "thTrofejMeat_zep_weasel001", "1");
SetLocalString(oModule, "thTrofejMisc_nw_dog", "kuze");
SetLocalString(oModule, "thTrofejMeat_nw_dog", "1");
SetLocalString(oModule, "thTrofejMisc_ry_pr_pes", "kuze");
SetLocalString(oModule, "thTrofejMeat_ry_pr_pes", "1");
SetLocalString(oModule, "thTrofejMisc_nw_blinkdog", "kuze");
SetLocalString(oModule, "thTrofejMeat_nw_blinkdog", "1");
SetLocalString(oModule, "thTrofejMisc_boar001", "kuze");
SetLocalString(oModule, "thTrofejMeat_boar001", "1");
SetLocalString(oModule, "thTrofejMisc_legwolf001", "ry_prvl_kuze");
SetLocalString(oModule, "thTrofejMeat_legwolf001", "2");
SetLocalInt(oModule, "thTrofejDiff_legwolf001", 200);
SetLocalString(oModule, "thTrofejMisc_ry_rosomak", "ry_ros_kuze");
SetLocalString(oModule, "thTrofejMeat_ry_rosomak", "1");
SetLocalInt(oModule, "thTrofejDiff_ry_rosomak", 200);
SetLocalString(oModule, "thTrofejMisc_wolverine001", "ry_ros_kuze");
SetLocalString(oModule, "thTrofejMeat_wolverine001", "1");
SetLocalInt(oModule, "thTrofejDiff_wolverine001", 200);
SetLocalString(oModule, "thTrofejMisc_nw_parrot", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_nw_parrot", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_017", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_017", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_018", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_018", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_019", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_019", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_016", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_016", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_020", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_020", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_024", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_024", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_025", "ry_pap_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_025", 50);
SetLocalString(oModule, "thTrofejMisc_zep_bird_023", "ry_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_023", 10);
SetLocalString(oModule, "thTrofejMisc_zep_bird_022", "ry_peri");
SetLocalInt(oModule, "thTrofejDiff_zep_bird_022", 10);
SetLocalString(oModule, "thTrofejMisc_zep_antelope001", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_zep_antelope001", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_zep_antelope001", 200);
SetLocalString(oModule, "thTrofejMisc_zep_antelopeb001", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_zep_antelopeb001", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_zep_antelopeb001", 200);
SetLocalString(oModule, "thTrofejMisc_zep_gazelle001", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_zep_gazelle001", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_zep_gazelle001", 200);
SetLocalString(oModule, "thTrofejMisc_cnrawhitestag", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_cnrawhitestag", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_cnrawhitestag", 200);
SetLocalString(oModule, "thTrofejMisc_cnradeer", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_cnradeer", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_cnradeer", 200);
SetLocalString(oModule, "thTrofejMisc_nw_deer", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_nw_deer", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_nw_deer", 200);
SetLocalString(oModule, "thTrofejMisc_nw_deerstag", "cnrleathdeer");
SetLocalString(oModule, "thTrofejMeat_nw_deerstag", "ry_parozi");
SetLocalInt(oModule, "thTrofejDiff_nw_deerstag", 200);
SetLocalString(oModule, "thTrofejMisc_cnraraven", "cnrfeatherraven");
SetLocalInt(oModule, "thTrofejDiff_cnraraven", 50);
SetLocalString(oModule, "thTrofejMisc_nw_raven", "cnrfeatherraven");
SetLocalInt(oModule, "thTrofejDiff_nw_raven", 50);
SetLocalString(oModule, "thTrofejMisc_zep_owl_007", "cnrfeatherowl");
SetLocalInt(oModule, "thTrofejDiff_zep_owl_007", 50);
SetLocalString(oModule, "thTrofejMisc_cnraowl", "cnrfeatherowl");
SetLocalInt(oModule, "thTrofejDiff_cnraowl", 50);
SetLocalString(oModule, "thTrofejMisc_cnrafalcon", "cnrfeatherfalcon");
SetLocalInt(oModule, "thTrofejDiff_cnrafalcon", 80);
SetLocalString(oModule, "thTrofejMisc_nw_raptor001", "cnrfeatherfalcon");
SetLocalInt(oModule, "thTrofejDiff_nw_raptor001", 80);
SetLocalString(oModule, "thTrofejMisc_tagry_fertox", "ry_kuz_fertox");
SetLocalInt(oModule, "thTrofejDiff_tagry_fertox", 5);
SetLocalString(oModule, "thTrofejMisc_tagry_krysa", "cnrskinrat");
SetLocalInt(oModule, "thTrofejDiff_tagry_krysa", 1);
SetLocalString(oModule, "thTrofejMisc_tagry_jezevec", "cnrskinbadger");
SetLocalString(oModule, "thTrofejMeat_tagry_jezevec", "1");
SetLocalInt(oModule, "thTrofejDiff_tagry_jezevec", 30);
SetLocalString(oModule, "thTrofejMisc_tagry_divocak", "cnrskinboar");
SetLocalString(oModule, "thTrofejMeat_tagry_divocak", "1");
SetLocalInt(oModule, "thTrofejDiff_tagry_divocak", 30);
SetLocalString(oModule, "thTrofejMisc_tagME_MED_JES", "ry_skalm_kuze");
SetLocalString(oModule, "thTrofejMeat_tagME_MED_JES", "1");
SetLocalInt(oModule, "thTrofejDiff_tagME_MED_JES", 50);
SetLocalString(oModule, "thTrofejMisc_tagNW_DIREWOLF", "ry_litvlk_kuze");
SetLocalString(oModule, "thTrofejMeat_tagNW_DIREWOLF", "1");
SetLocalInt(oModule, "thTrofejDiff_tagNW_DIREWOLF", 100);
SetLocalString(oModule, "thTrofejMisc_zep_owlbear_up", "kuzeowlbeara");
SetLocalString(oModule, "thTrofejMeat_zep_owlbear_up", "1");
SetLocalInt(oModule, "thTrofejDiff_zep_owlbear_up", 150);
SetLocalString(oModule, "thTrofejMisc_alansijskytygr", "kuzealansijskeho");
SetLocalString(oModule, "thTrofejMeat_alansijskytygr", "2");
SetLocalInt(oModule, "thTrofejDiff_alansijskytygr", 600);
SetLocalString(oModule, "thTrofejMisc_ry_grifon", "ry_grif_peri");
SetLocalInt(oModule, "thTrofejDiff_ry_grifon", 340);
SetLocalString(oModule, "thTrofejMisc_zep_razorboar001", "ry_kel_prase");
SetLocalInt(oModule, "thTrofejDiff_zep_razorboar001", 260);
SetLocalString(oModule, "thTrofejMisc_nw_bulette", "supinybuleta");
SetLocalInt(oModule, "thTrofejDiff_nw_bulette", 200);
SetLocalString(oModule, "thTrofejMisc_grayrend001", "ry_sedtr_kuze");
SetLocalInt(oModule, "thTrofejDiff_grayrend001", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_stirga", "ry_vykstirga");
SetLocalInt(oModule, "thTrofejDiff_tagry_stirga", 20);
SetLocalString(oModule, "thTrofejMisc_tagry_wefr", "ry_sup_wefr");
SetLocalInt(oModule, "thTrofejDiff_tagry_wefr", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_drapatec", "ry_drap_maso");
SetLocalInt(oModule, "thTrofejDiff_tagry_drapatec", 80);
SetLocalString(oModule, "thTrofejMisc_netopyrodlak", "ry_netdl_kridlo");
SetLocalInt(oModule, "thTrofejDiff_netopyrodlak", 160);
SetLocalString(oModule, "thTrofejMisc_nw_beastmalar001", "cnrskinmalar");
SetLocalInt(oModule, "thTrofejDiff_nw_beastmalar001", 150);
SetLocalString(oModule, "thTrofejMisc_cnramalar", "cnrskinmalar");
SetLocalInt(oModule, "thTrofejDiff_cnramalar", 150);
SetLocalString(oModule, "thTrofejMisc_tagry_tygrodlak", "ry_tygrodl_kuze");
SetLocalInt(oModule, "thTrofejDiff_tagry_tygrodlak", 300);
SetLocalString(oModule, "thTrofejMisc_ry_yetti_boj", "ry_kuz_yetti");
SetLocalInt(oModule, "thTrofejDiff_ry_yetti_boj", 320);
SetLocalString(oModule, "thTrofejMisc_ry_yetti_hum", "ry_kuz_yetti");
SetLocalInt(oModule, "thTrofejDiff_ry_yetti_hum", 320);
SetLocalString(oModule, "thTrofejMisc_ry_yetti_obri", "ry_kuz_yetti");
SetLocalInt(oModule, "thTrofejDiff_ry_yetti_obri", 320);
SetLocalString(oModule, "thTrofejMisc_nw_trollboss", "me_misc_srdtrch");
SetLocalString(oModule, "thTrofejMisc_nw_skelwarr01", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_nw_skeleton", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_nw_skelwarr02", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_nw_skelchief", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_nw_skelpriest", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_nw_skelmage", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_kostlivecbojovni", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_kostliveclucistn", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_kostlivecmag", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_kostvlivecbojovn", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_skelchief001", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_skeleton001", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_tagry_kostlivec", "me_kloubk");
SetLocalString(oModule, "thTrofejMisc_bodak001", "me_kloubk");
SetLocalInt(oModule, "thTrofejDiff_bodak001", 250);
SetLocalString(oModule, "thTrofejMisc_nw_lich001", "kh_zublicha");
SetLocalInt(oModule, "thTrofejDiff_nw_lich001", 320);
SetLocalString(oModule, "thTrofejMisc_nw_lich003", "kh_zublicha");
SetLocalInt(oModule, "thTrofejDiff_nw_lich003", 320);
SetLocalString(oModule, "thTrofejMisc_nw_lichboss", "kh_zublicha");
SetLocalInt(oModule, "thTrofejDiff_nw_lichboss", 320);
SetLocalString(oModule, "thTrofejMisc_tagry_ghoul", "ry_ghoul_jatra");
SetLocalString(oModule, "thTrofejMisc_barghest2", "ry_bargh_kuze");
SetLocalInt(oModule, "thTrofejDiff_barghest2", 200);
SetLocalString(oModule, "thTrofejMisc_zep_barghest", "ry_bargh_kuze");
SetLocalInt(oModule, "thTrofejDiff_zep_barghest", 200);
SetLocalString(oModule, "thTrofejMisc_nw_slaadred", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaadred", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaadbl", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaadbl", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaaddthboss", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaaddthboss", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaadgryboss", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaadgryboss", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaaddeth", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaaddeth", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaadgray", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaadgray", 120);
SetLocalString(oModule, "thTrofejMisc_nw_slaadgrn", "nw_it_msmlmisc10");
SetLocalInt(oModule, "thTrofejDiff_nw_slaadgrn", 120);
SetLocalString(oModule, "thTrofejMisc_nw_rakshasa", "nw_it_msmlmisc09");
SetLocalInt(oModule, "thTrofejDiff_nw_rakshasa", 150);
SetLocalString(oModule, "thTrofejMisc_tagry_mephit", "ry_srdce_meph");
SetLocalInt(oModule, "thTrofejDiff_tagry_mephit", 80);
SetLocalString(oModule, "thTrofejMisc_krenshar2", "kuzekrenshara001");
SetLocalString(oModule, "thTrofejMeat_krenshar2", "1");
SetLocalInt(oModule, "thTrofejDiff_krenshar2", 150);
SetLocalString(oModule, "thTrofejMisc_nw_krenshar", "kuzekrenshara001");
SetLocalString(oModule, "thTrofejMeat_nw_krenshar", "1");
SetLocalInt(oModule, "thTrofejDiff_nw_krenshar", 150);
SetLocalString(oModule, "thTrofejMisc_mantikora1", "ry_mant_osten");
SetLocalInt(oModule, "thTrofejDiff_mantikora1", 230);
SetLocalString(oModule, "thTrofejMisc_zep_manticore", "ry_mant_osten");
SetLocalInt(oModule, "thTrofejDiff_zep_manticore", 230);
SetLocalString(oModule, "thTrofejMisc_x0_manticore", "ry_mant_osten");
SetLocalInt(oModule, "thTrofejDiff_x0_manticore", 230);
SetLocalString(oModule, "thTrofejMisc_diretiger002", "ry_baz_oko");
SetLocalInt(oModule, "thTrofejDiff_diretiger002", 400);
SetLocalString(oModule, "thTrofejMisc_ja_cockatrice", "peri_plivnika");
SetLocalInt(oModule, "thTrofejDiff_ja_cockatrice", 200);
SetLocalString(oModule, "thTrofejMisc_x0_gorgon", "me_misc_srdgorg");
SetLocalInt(oModule, "thTrofejDiff_x0_gorgon", 290);
SetLocalString(oModule, "thTrofejMisc_cnraworg", "cnrskinworg");
SetLocalInt(oModule, "thTrofejDiff_cnraworg", 160);
SetLocalString(oModule, "thTrofejMisc_nw_worg", "cnrskinworg");
SetLocalInt(oModule, "thTrofejDiff_nw_worg", 160);
SetLocalString(oModule, "thTrofejMisc_worgh", "cnrskinworg");
SetLocalInt(oModule, "thTrofejDiff_worgh", 160);
SetLocalString(oModule, "thTrofejMisc_tagry_vraz_vino", "ry_popsl_vyh");
SetLocalInt(oModule, "thTrofejDiff_tagry_vraz_vino", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_zimni_vlk", "cnrskinwinwolf");
SetLocalInt(oModule, "thTrofejDiff_tagry_zimni_vlk", 200);
SetLocalString(oModule, "thTrofejMisc_ettercap001", "me_ethetzl");
SetLocalInt(oModule, "thTrofejDiff_ettercap001", 100);
SetLocalString(oModule, "thTrofejMisc_umberhulk001", "ry_klep_klep");
SetLocalInt(oModule, "thTrofejDiff_umberhulk001", 160);
SetLocalString(oModule, "thTrofejMisc_zabijackevino", "ry_vino_spory");
SetLocalInt(oModule, "thTrofejDiff_zabijackevino", 200);
SetLocalString(oModule, "thTrofejMisc_willowisp001", "ry_blud_esence");
SetLocalInt(oModule, "thTrofejDiff_willowisp001", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_hak_das", "ry_hak_krunyr");
SetLocalInt(oModule, "thTrofejDiff_tagry_hak_das", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_mutant", "ry_mut_sliz");
SetLocalInt(oModule, "thTrofejDiff_tagry_mutant", 50);
SetLocalString(oModule, "thTrofejMisc_tagry_beholder", "ry_behold_oko");
SetLocalInt(oModule, "thTrofejDiff_tagry_beholder", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_klepetnatci", "ry_srdce_klepet");
SetLocalInt(oModule, "thTrofejDiff_tagry_klepetnatci", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_klep_psyonik", "ry_klpsyon_moz");
SetLocalInt(oModule, "thTrofejDiff_tagry_klep_psyonik", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_kolonie_spor", "ry_zrspor_myk");
SetLocalInt(oModule, "thTrofejDiff_tagry_kolonie_spor", 200);
SetLocalString(oModule, "thTrofejMisc_nw_btlfire", "nw_it_msmlmisc08");
SetLocalInt(oModule, "thTrofejDiff_nw_btlfire", 20);
SetLocalString(oModule, "thTrofejMisc_ry_btlfire003", "nw_it_msmlmisc08");
SetLocalInt(oModule, "thTrofejDiff_ry_btlfire003", 20);
SetLocalString(oModule, "thTrofejMisc_zep_beetlefir001", "nw_it_msmlmisc08");
SetLocalInt(oModule, "thTrofejDiff_zep_beetlefir001", 20);
SetLocalString(oModule, "thTrofejMisc_broukohnivak", "it_cmat_elmw001");
SetLocalInt(oModule, "thTrofejDiff_broukohnivak", 360);
SetLocalString(oModule, "thTrofejMisc_kralovnabroukuoh", "kh_krovohnivkral");
SetLocalInt(oModule, "thTrofejDiff_kralovnabroukuoh", 400);
SetLocalString(oModule, "thTrofejMisc_broukkyselac", "it_cmat_elmw003");
SetLocalInt(oModule, "thTrofejDiff_broukkyselac", 360);
SetLocalString(oModule, "thTrofejMisc_zep_scorp004", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorp004", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorph005", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorph005", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorpg005", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorpg005", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorph006", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorph006", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorpg004", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorpg004", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorph004", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorph004", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorp005", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorp005", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorpg005", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorpg005", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorph006", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorph006", 10);
SetLocalString(oModule, "thTrofejMisc_zep_scorp006", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_zep_scorp006", 10);
SetLocalString(oModule, "thTrofejMisc_ry_stir_maly", "bodakstira");
SetLocalInt(oModule, "thTrofejDiff_ry_stir_maly", 10);
SetLocalString(oModule, "thTrofejMisc_nw_btlbomb", "cnrbellbomb");
SetLocalInt(oModule, "thTrofejDiff_nw_btlbomb", 200);
SetLocalString(oModule, "thTrofejMisc_obrivosa", "zihadlo_vosy");
SetLocalInt(oModule, "thTrofejDiff_obrivosa", 10);
SetLocalString(oModule, "thTrofejMisc_nw_btlstink", "cnrstinkgland");
SetLocalInt(oModule, "thTrofejDiff_nw_btlstink", 12);
SetLocalString(oModule, "thTrofejMisc_btlstag001", "ry_kr_rohac");
SetLocalInt(oModule, "thTrofejDiff_btlstag001", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_brouk", "ry_br_krovky");
SetLocalInt(oModule, "thTrofejDiff_tagry_brouk", 50);
SetLocalString(oModule, "thTrofejMisc_tagry_brouk_2", "ry_br_krovky_2");
SetLocalInt(oModule, "thTrofejDiff_tagry_brouk_2", 70);
SetLocalString(oModule, "thTrofejMisc_tagry_krab", "masokraba001");
SetLocalInt(oModule, "thTrofejDiff_tagry_krab", 30);
SetLocalString(oModule, "thTrofejMisc_tagry_krab_obr", "ry_mas_obrkr");
SetLocalInt(oModule, "thTrofejDiff_tagry_krab_obr", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_ohn_brouk", "me_ohnbro");
SetLocalInt(oModule, "thTrofejDiff_tagry_ohn_brouk", 50);
SetLocalString(oModule, "thTrofejMisc_tagry_ant_larva", "ry_stav_larva");
SetLocalInt(oModule, "thTrofejDiff_tagry_ant_larva", 50);
SetLocalString(oModule, "thTrofejMisc_tagry_ant_kral", "ry_mrkral_kridl");
SetLocalInt(oModule, "thTrofejDiff_tagry_ant_kral", 250);
SetLocalString(oModule, "thTrofejMisc_tagry_mrchozrout", "ry_mrchzr_krev");
SetLocalInt(oModule, "thTrofejDiff_tagry_mrchozrout", 60);
SetLocalString(oModule, "thTrofejMisc_tagry_rudstir", "ry_rudst_krun");
SetLocalInt(oModule, "thTrofejDiff_tagry_rudstir", 80);
SetLocalString(oModule, "thTrofejMisc_tagry_cerstir", "ry_cerst_krun");
SetLocalInt(oModule, "thTrofejDiff_tagry_cerstir", 80);
SetLocalString(oModule, "thTrofejMisc_zep_blackpudd001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_zep_blackpudd001", 50);
SetLocalString(oModule, "thTrofejMisc_zep_brownpudd001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_zep_brownpudd001", 50);
SetLocalString(oModule, "thTrofejMisc_zep_crystaloo001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_zep_crystaloo001", 50);
SetLocalString(oModule, "thTrofejMisc_zep_greenslim001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_zep_greenslim001", 50);
SetLocalString(oModule, "thTrofejMisc_grayooze001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_grayooze001", 50);
SetLocalString(oModule, "thTrofejMisc_ochrejellylrg001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_ochrejellylrg001", 50);
SetLocalString(oModule, "thTrofejMisc_ochrejellymed001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_ochrejellymed001", 50);
SetLocalString(oModule, "thTrofejMisc_ochrejellysml001", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_ochrejellysml001", 50);
SetLocalString(oModule, "thTrofejMisc_tagnw_ochrejellylrg", "ry_sliz_ichor");
SetLocalInt(oModule, "thTrofejDiff_tagnw_ochrejellylrg", 30);
SetLocalString(oModule, "thTrofejMisc_gypsy004", "it_cmat_elmw004");
SetLocalInt(oModule, "thTrofejDiff_gypsy004", 160);
SetLocalString(oModule, "thTrofejMisc_gypsy005", "it_cmat_elmw004");
SetLocalInt(oModule, "thTrofejDiff_gypsy005", 160);
SetLocalString(oModule, "thTrofejMisc_gypsy006", "it_cmat_elmw004");
SetLocalInt(oModule, "thTrofejDiff_gypsy006", 160);
SetLocalString(oModule, "thTrofejMisc_bandit007", "it_cmat_elmw005");
SetLocalInt(oModule, "thTrofejDiff_bandit007", 160);
SetLocalString(oModule, "thTrofejMisc_dwarfmerc005", "it_cmat_elmw005");
SetLocalInt(oModule, "thTrofejDiff_dwarfmerc005", 161);
SetLocalString(oModule, "thTrofejMisc_gypsy008", "it_cmat_elmw005");
SetLocalInt(oModule, "thTrofejDiff_gypsy008", 160);
SetLocalString(oModule, "thTrofejMisc_halfmerc005", "it_cmat_elmw005");
SetLocalInt(oModule, "thTrofejDiff_halfmerc005", 160);
SetLocalString(oModule, "thTrofejMisc_humanmerc005", "it_cmat_elmw005");
SetLocalInt(oModule, "thTrofejDiff_humanmerc005", 160);
SetLocalString(oModule, "thTrofejMisc_ry_krokodyl", "ry_krok_kuze");
SetLocalInt(oModule, "thTrofejDiff_ry_krokodyl", 120);
SetLocalString(oModule, "thTrofejMisc_tagry_harpy_hag", "ry_hag_srdce");
SetLocalInt(oModule, "thTrofejDiff_tagry_harpy_hag", 220);
SetLocalString(oModule, "thTrofejMisc_tagry_drapatec", "ry_drap_maso");
SetLocalInt(oModule, "thTrofejDiff_tagry_drapatec", 80);
SetLocalString(oModule, "thTrofejMisc_sirena", "kh_hlassireny");
SetLocalInt(oModule, "thTrofejDiff_sirena", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_aboleth", "ry_abol_chap");
SetLocalInt(oModule, "thTrofejDiff_tagry_aboleth", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_kortix", "ry_sup_kortix");
SetLocalInt(oModule, "thTrofejDiff_tagry_kortix", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_krivilie", "ry_krev_kriv");
SetLocalInt(oModule, "thTrofejDiff_tagry_krivilie", 200);
SetLocalString(oModule, "thTrofejMisc_ry_rytirzkazy_1", "tc_troproryt");
SetLocalInt(oModule, "thTrofejDiff_ry_rytirzkazy_1", 100);
SetLocalString(oModule, "thTrofejMisc_ry_rytirzkazy_2", "tc_troproryt");
SetLocalInt(oModule, "thTrofejDiff_ry_rytirzkazy_2", 100);
SetLocalString(oModule, "thTrofejMisc_ry_rytirzkazy_bs", "tc_troproryt");
SetLocalInt(oModule, "thTrofejDiff_ry_rytirzkazy_bs", 100);
SetLocalString(oModule, "thTrofejMisc_bodak001", "nw_it_msmlmisc06");
SetLocalInt(oModule, "thTrofejDiff_bodak001", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_pavouk_m", "tc_alcjedvak1");
SetLocalInt(oModule, "thTrofejDiff_tagry_pavouk_m", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_pavouk_s", "tc_alcjedvak2");
SetLocalInt(oModule, "thTrofejDiff_tagry_pavouk_s", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_pavuk_v", "tc_alcjedvak3");
SetLocalInt(oModule,    "thTrofejDiff_tagry_pavuk_v", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_had_m", "tc_alcjedvak1");
SetLocalInt(oModule, "thTrofejDiff_tagry_had_m", 100);
SetLocalString(oModule, "thTrofejMisc_tagry_had_s", "tc_alcjedvak2");
SetLocalInt(oModule, "thTrofejDiff_tagry_had_s", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_had_v", "tc_alcjedvak3");
SetLocalInt(oModule, "thTrofejDiff_tagry_had_v", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_ettercap_str", "me_ethetzl");
SetLocalInt(oModule, "thTrofejDiff_tagry_ettercap_str", 300);
SetLocalString(oModule, "thTrofejMisc_tagcnrarat", "cnrskinrat");
SetLocalInt(oModule, "thTrofejDiff_tagcnrarat", 300);
SetLocalString(oModule, "thTrofejMisc_tagNW_WILLOWISP", "ry_blud_esence");
SetLocalInt(oModule, "thTrofejDiff_tagNW_WILLOWISP", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_kys_kostka_1", "ry_kys_esence");
SetLocalInt(oModule,    "thTrofejDiff_tagry_kys_kostka_1", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_ozivla_kys_1", "ry_kys_esence");
SetLocalInt(oModule,    "thTrofejDiff_tagry_ozivla_kys_1", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_mykanoid", "sporymykoida");
SetLocalInt(oModule,    "thTrofejDiff_tagry_mykanoid", 500);
SetLocalString(oModule, "thTrofejMisc_tagry_prast_tygr", "ry_pr_tygr_kuze");
SetLocalInt(oModule,    "thTrofejDiff_tagry_prast_tygr", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_prast_medved", "ry_pr_medv_kuze");
SetLocalInt(oModule,    "thTrofejDiff_tagry_prast_medved", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_pral_op", "ry_pr_op_kuze");
SetLocalInt(oModule,    "thTrofejDiff_tagry_pral_op", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_prales_prase", "ry_pr_div_kuze");
SetLocalInt(oModule,    "thTrofejDiff_tagry_prales_prase", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_prast_orel", "ry_pr_orel_peri");
SetLocalInt(oModule,    "thTrofejDiff_tagry_prast_orel", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_reaver", "ry_rud_gh_jatra");
SetLocalInt(oModule,    "thTrofejDiff_tagry_reaver", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_pr_komar", "ry_pr_kom_kridlo");
SetLocalInt(oModule,    "thTrofejDiff_tagry_pr_komar", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_pr_kostl", "ry_st_kostl_kost");
SetLocalInt(oModule,    "thTrofejDiff_tagry_pr_kostl", 300);
SetLocalString(oModule, "thTrofejMisc_tagry_kys_zploz_1", "ry_srdce_splkys");
SetLocalInt(oModule,    "thTrofejDiff_tagry_kys_zploz_1", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_kys_zploz_2", "ry_srdce_splkys");
SetLocalInt(oModule,    "thTrofejDiff_tagry_kys_zploz_2", 600);
SetLocalString(oModule, "thTrofejMisc_tagry_ml_slaad", "ry_jaz_ml_slaad");
SetLocalInt(oModule,    "thTrofejDiff_tagry_ml_slaad", 200);
SetLocalString(oModule, "thTrofejMisc_tagry_slaad", "ry_jaz_slaad");
SetLocalInt(oModule,    "thTrofejDiff_tagry_slaad", 400);
SetLocalString(oModule, "thTrofejMisc_tagnetopyrodlak", "ry_netdl_kridlo");
SetLocalInt(oModule,    "thTrofejDiff_tagnetopyrodlak", 400);
SetLocalString(oModule, "thTrofejMisc_tagNetopyrodlak", "ry_netdl_kridlo");
SetLocalInt(oModule,    "thTrofejDiff_tagNetopyrodlak", 400);
SetLocalString(oModule, "thTrofejMisc_tagry_salamandr", "ry_srdce_salam");
SetLocalInt(oModule,    "thTrofejDiff_tagry_salamandr", 350);
SetLocalString(oModule, "thTrofejMisc_tagry_ohn_zploz", "ry_srdce_sploh");
SetLocalInt(oModule,    "thTrofejDiff_tagry_ohn_zploz", 350);
SetLocalString(oModule, "thTrofejMisc_tagry_kostlivec_v", "ry_kloub_stkost");
SetLocalInt(oModule,    "thTrofejDiff_tagry_kostlivec_v", 400);
SetLocalString(oModule, "thTrofejMisc_tagry_bodak", "ry_zub_bodak");
SetLocalInt(oModule,    "thTrofejDiff_tagry_bodak", 350);
SetLocalString(oModule, "thTrofejMisc_tagZEP_BARGHEST", "ry_m_barg_kuz");
SetLocalInt(oModule,    "thTrofejDiff_tagZEP_BARGHEST", 200);
*/


/* TROFEJE END */
}
