/*
Vrati 1 pokud ma postava zamereni zbran na blizko, 2 pokud ma specializaci, -1 pokud nema ani jedno.
*/

int GetWeaponFocusOrSpecializationMelee(object oPC)
{
    if (
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_BASTARD_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_BATTLE_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_CLUB,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_DAGGER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_DIRE_MACE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_DOUBLE_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_DWAXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_GREAT_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_GREAT_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_HALBERD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_HAND_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_HEAVY_FLAIL,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_KAMA,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_KATANA,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_KUKRI,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LIGHT_FLAIL,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LIGHT_HAMMER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LIGHT_MACE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LONG_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_MORNING_STAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_RAPIER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SCIMITAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SCYTHE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SHORT_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SICKLE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SPEAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_STAFF,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_TRIDENT,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_TWO_BLADED_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_UNARMED_STRIKE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_WAR_HAMMER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_WHIP,oPC))
    )
    {
        return 2;
    }
    if (
    (GetHasFeat(FEAT_WEAPON_FOCUS_BASTARD_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_BATTLE_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_CLUB,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_DAGGER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_DIRE_MACE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_DOUBLE_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_DWAXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_GREAT_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_GREAT_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_HALBERD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_HAND_AXE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_HEAVY_FLAIL,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_KAMA,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_KATANA,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_KUKRI,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LIGHT_FLAIL,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LIGHT_HAMMER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LIGHT_MACE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LONG_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_MORNING_STAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_RAPIER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SCIMITAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SCYTHE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SHORT_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SICKLE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SPEAR,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_STAFF,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_TRIDENT,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_TWO_BLADED_SWORD,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_UNARMED_STRIKE,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_WAR_HAMMER,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_WHIP,oPC))
    )
    {
        return 1;
    }
    return -1;
}



/*
Vrati 1 pokud ma postava zamereni zbran na dalku, 2 pokud ma specializaci, 0 pokud nema ani jedno.
*/

int GetWeaponFocusOrSpecializationRanged(object oPC)
{
    if (
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_DART,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_HEAVY_CROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LIGHT_CROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_LONGBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SHORTBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SHURIKEN,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_SLING,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_SPECIALIZATION_THROWING_AXE,oPC))
    )
    {
        return 2;
    }

    if (
    (GetHasFeat(FEAT_WEAPON_FOCUS_DART,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_HEAVY_CROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LIGHT_CROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_LONGBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SHORTBOW,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SHURIKEN,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_SLING,oPC)) ||
    (GetHasFeat(FEAT_WEAPON_FOCUS_THROWING_AXE,oPC))
    )
    {
        return 1;
    }
    return -1;
}


//EPICK0


/*
Vrati 1 pokud ma postava zamereni zbran na blizko, 2 pokud ma specializaci, -1 pokud nema ani jedno.
*/

int GetEpicWeaponFocusOrSpecializationMelee(object oPC)
{
    if (
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_BASTARDSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_BATTLEAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_CLUB,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_DAGGER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_DIREMACE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_DOUBLEAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_DWAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_GREATAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_GREATSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_HALBERD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_HANDAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYFLAIL,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_KAMA,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_KATANA,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_KUKRI,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTFLAIL,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTHAMMER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTMACE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LONGSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_MORNINGSTAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_RAPIER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SCIMITAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SCYTHE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SICKLE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSPEAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_QUARTERSTAFF,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_TRIDENT,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_TWOBLADEDSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_UNARMED,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_WARHAMMER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_WHIP,oPC))
    )
    {
        return 2;
    }
    if (
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_BASTARDSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_BATTLEAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_CLUB,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_DAGGER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_DIREMACE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_DOUBLEAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_DWAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_GREATAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_GREATSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_HALBERD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_HANDAXE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_HEAVYFLAIL,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_KAMA,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_KATANA,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_KUKRI,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LIGHTFLAIL,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LIGHTHAMMER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LIGHTMACE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LONGSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_MORNINGSTAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_RAPIER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SCIMITAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SCYTHE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SHORTSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SICKLE,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SHORTSPEAR,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_QUARTERSTAFF,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_TRIDENT,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_TWOBLADEDSWORD,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_UNARMED,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_WARHAMMER,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_WHIP,oPC))
    )
    {
        return 1;
    }
    return 0;
}




/*
Vrati 1 pokud ma postava zamereni zbran na dalku, 2 pokud ma specializaci, 0 pokud nema ani jedno.
*/

int GetEpicWeaponFocusOrSpecializationRanged(object oPC)
{
    if (
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_DART,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYCROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTCROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_LONGBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SHURIKEN,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_SLING,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_SPECIALIZATION_THROWINGAXE,oPC))
    )
    {
        return 2;
    }

    if (
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_DART,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_HEAVYCROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LIGHTCROSSBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_LONGBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SHORTBOW,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SHURIKEN,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_SLING,oPC)) ||
    (GetHasFeat(FEAT_EPIC_WEAPON_FOCUS_THROWINGAXE,oPC))
    )
    {
        return 1;
    }
    return 0;
}




